# Generated by Django 3.2 on 2021-07-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthController', '0003_todoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todoitem',
        ),
    ]
