# Generated by Django 3.2 on 2021-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthController', '0004_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
